import Head from 'next/head'
import Navbar from '../components/Navbar'
import Image from 'next/image'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Experience from '../components/Experience'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Zahra Benmohamed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon1.png" />
      </Head>
      <Navbar/>
      <Main />
      <About/>
      <Experience/>
      <Skills/>
      <Projects/>
      <Contact/>

      
    </div>
  )
}
